### ISSUE TITLE
Extend IO I2C address is not 0x27

### ISSUE THREAD

**Issue by mlaber** [m5stack/UIFlow-Code#4]
By scanning my i2c bus i recognized that my M5 extended I/O unit (SN: U01100383) has I2C address 0x20 instead 0x27 as described in documentation an product docs of the extended I/O unit. 
in the m5stack micro python libraries "0x27" is hard wired as address so the module is not found by the used libraries and could not be used with this libs and M5Flow.
In the [data sheet](http://www.ti.com/lit/ds/symlink/pca9554.pdf) of the used PCA9554W controller table 2 on page 17 defines the pins used for hardware address selection. For 0x27 all three dress pins (A0, A1, A2) have to be pulled to "high".
When the address pins are pulled to "low" or are not connected this might lead to address "0x20"  . I could not ensure that this was only a production problem for some extended I/O units or if its an major design bug in your hardware but as a result your code and libs which references on 0x27 don't match your hardware design of the extended I/O unit (at least for some production batches).

**Comment by EeeeBin** [comment]
Thx for your msg.
We would check our in-stock items. and get back to you sooner

**Comment by mlaber** [comment]
Any results so far?
I bought two additional extended I/O units beside the fact that no serial number is printed on the modules their behaviour is identical to the first series. The unit still uses 0x20 as I2C address and not 0x27 which is hard coded in your flowlib/units/_ext_io.py  library.
**This is a major issue for all your customers who could not use the extended I/O module with UI Flow. Please fix this bug by just setting the right address in the module.** 

Accessing the module with  the native I2C app is possible e.g.:
_def buttonB_wasPressed():
  # global params
  i2c0 = i2c_bus.easyI2C(i2c_bus.PORTA, 0x20)
  wait_ms(20)
  i2c0.write_u8(0x03, 0x00)
  wait_ms(20)
  i2c0.write_u8(0x01, 0x00)
  pass
btnB.wasPressed(buttonB_wasPressed)_

**So its just fixing your library by setting the correct address. **
If you´ll publish the _ext_io.py module in your github repo i can send you a PR.

**Comment by kapest007** [comment]
Also I just fell for it! unfortunately I cannot continue my project in Blockly. I'm surprised that this bug is known since January 3rd and has not been fixed until today. I am very disappointed. I hope that this bug will be fixed soon.

Apart from that I'm thrilled with M5Stack.

Peter

**Comment by kapest007** [comment]
Ich habe die Unit geöffnet und festgestellt, dass intern die I2C-Adresse geändert werden kann. Die Kontakte von R6...R8 mit einer Lötzinn Brücke versehen. Dann ist Adresse 0x27 eingestellt und alles funktioniert. 

I opened the unit and found that internally the I2C address can be changed. The contacts of R6...R8 have to be soldered. Then address 0x27 is set and everything works. 

Peter

**Comment by mlaber** [comment]
> I opened the unit and found that internally the I2C address can be changed. The contacts of R6...R8 have to be soldered. Then address 0x27 is set and everything works.
> 
Hi Peter,
thats a good workaround and i will probably fix the hardware that it machetes the software.
But i guess m5stack should fix his code (which could be done in minutes) that the Extend IO module could be used by alle users out of the box.
The convenience factor ist one of the biggest benefits of the m5stack platform and extensions if i have to solder i also could use a plain ESP32 and android. 😏

**Comment by kapest007** [comment]
Gesendet: Donnerstag, 12. März 2020 um 18:31 UhrHi, Markus,
You're absolutely right, M5Stack should be able to correct this very quickly. And then implement an input for the address, then you can use 8 Extend I/O's at the same time. But with its own power supply.
Von: "Markus Laber" <notifications@github.com>
An: m5stack/UIFlow-Code <UIFlow-Code@noreply.github.com>
Cc: kapest007 <kpstoeck@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [m5stack/UIFlow-Code] Extend IO I2C address is not 0x27 (#4)


 


I opened the unit and found that internally the I2C address can be changed. The contacts of R6...R8 have to be soldered. Then address 0x27 is set and everything works.


Hi Peter,
thats a good workaround and i will probably fix the hardware that it machetes the software.
But i guess m5stack should fix his code (which could be done in minutes) that the Extend IO module could be used by alle users out of the box.
The convenience factor ist one of the biggest benefits of the m5stack platform and extensions if i have to solder i also could use a plain ESP32 and android. 😏

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

 

Hi, Markus,
You're absolutely right, M5Stack should be able to correct this very quickly. And then implement an input for the address, then you can use 8 Extend I/O's at the same time. But with its own power supply.

**Comment by EeeeBin** [comment]
I am very very sorry forgot to update, it maybe fixed in 1.4.5.1, pls try
it again

**Comment by mlaber** [comment]
> I am very very sorry forgot to update, it maybe fixed in 1.4.5.1, pls try it again

Sorry for the delay, but it took some time to get again the hardware and verify the fix.  1.4.5.x now uses the correct I2C address 0x20 and the M5 extended I/O unit  can now be used without nasty workarounds. Thank you.
